Added Special Circumstances and Military Pay Types
department-of-veterans-affairs/lighthouse-mock-benefits-gateway-services pull request #18
Opened 2021-11-12 19:10 UTC by KevinCranmer

Adding Special Circumstances and Military Pay Types to mock BGS for reference data service. These are part of the SvnTypeV2Endpoint.
[API-11275](https://vajira.max.gov/browse/API-11275)
[API-11271](https://vajira.max.gov/browse/API-11271)

2021-11-12 20:54 UTC, jblefkove-va approved these changes
:shipit:

2021-11-12 20:59 UTC, jblefkove-va requested changes
add integration tests

2021-11-12 22:59 UTC, jblefkove-va approved these changes
:shipit:

2021-11-13 00:15 UTC, esubocz-va approved these changes

2021-11-13 00:21 UTC, merged